import AppKit
import Combine
import UniformTypeIdentifiers

@MainActor
public final class ClipboardMonitor: ObservableObject {
    @Published public private(set) var isPaused = false
    @Published public private(set) var notice: String?

    private let pasteboard: NSPasteboard
    private let history: ClipboardHistory
    private var timer: Timer?
    private var lastChangeCount: Int

    // Respect the shared clipboard conventions used by password managers and text expanders.
    public static let ignoredTypes = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type",
    ].map { NSPasteboard.PasteboardType($0) }

    public init(history: ClipboardHistory, pasteboard: NSPasteboard = .general) {
        self.history = history
        self.pasteboard = pasteboard
        // A new session starts empty, even if the system clipboard still contains an old copy.
        lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.35, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.08
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func setPaused(_ paused: Bool) {
        isPaused = paused
        // Items copied while paused are never picked up after resuming.
        lastChangeCount = pasteboard.changeCount
        notice = nil
    }

    public func clearHistory() {
        history.clear()
        lastChangeCount = pasteboard.changeCount
        notice = nil
    }

    public func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !isPaused else { return }
        notice = nil

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes),
              let item = pasteboard.pasteboardItems?.first else { return }

        var captured: ClipboardEntry?
        let imageTypes: [NSPasteboard.PasteboardType] = [
            .png, .tiff, .init("public.jpeg"), .init("com.compuserve.gif"), .init("public.heic"),
        ]
        for type in imageTypes where item.types.contains(type) {
            guard let data = item.data(forType: type) else { continue }
            if data.count > ClipboardHistory.maximumEntryBytes {
                notice = "Skipped an image larger than 32 MB."
                return
            }
            if let image = ClipboardEntry.image(data, type: type) {
                captured = image
                break
            }
        }

        if types.contains(.fileURL) {
            if let fileEntry = captureImageFile(),
               captured == nil || captured?.fingerprint == fileEntry.fingerprint {
                captured = fileEntry
            }
            // A file's path is not its image content; other file types remain outside the history.
            guard captured != nil else { return }
            // A valid pixel representation still works if its file reference is unavailable.
            notice = nil
        }

        if captured == nil, let value = item.string(forType: .string) {
            if value.utf8.count > ClipboardHistory.maximumEntryBytes {
                notice = "Skipped text larger than 32 MB."
                return
            }
            captured = ClipboardEntry.text(value)
        }

        // A source app may change the clipboard while providing a promised representation.
        guard pasteboard.changeCount == changeCount, let captured else { return }
        history.record(captured)
    }

    private func captureImageFile() -> ClipboardEntry? {
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true,
            .urlReadingContentsConformToTypes: [UTType.image.identifier],
        ]) as? [URL], let url = urls.first, url.isFileURL else { return nil }

        do {
            let data = try LocalImageFile.read(url)
            guard let entry = ClipboardEntry.imageFile(data, sourceFileURL: url) else {
                notice = "Couldn’t read this image format. Try copying it from Preview."
                return nil
            }
            return entry
        } catch LocalImageFile.ReadError.unavailableLocally {
            notice = "Open or download the image locally before copying it."
            return nil
        } catch LocalImageFile.ReadError.tooLarge {
            notice = "Skipped an image larger than 32 MB."
            return nil
        } catch LocalImageFile.ReadError.unsupported {
            return nil
        } catch {
            notice = "Couldn’t read the image file. Open it in Preview and copy the image."
            return nil
        }
    }

    @discardableResult
    public func restore(_ entry: ClipboardEntry) -> Bool {
        let item = entry.pasteboardItem()
        pasteboard.clearContents()
        let success = pasteboard.writeObjects([item])
        lastChangeCount = pasteboard.changeCount
        if success {
            history.promote(entry.id)
            notice = nil
        } else {
            notice = "Couldn’t copy this item. Please try again."
        }
        return success
    }
}
